### ISSUE TITLE
Remove breakpoint

### ISSUE THREAD

**Issue by tovop** [KonstantinChri/dnora#21]
Hi, thanks for providing such a useful tool.

Note that there is a **breakpoint** in line 95 of `dnora.bnd.read_ec()`. This triggers the Python debugger which in turn halts any script using it, basically preventing unsupervised execution.

Please remove it.

```python, highligt=2
restricted_area = self.get_restricted_area()
breakpoint()
nc_file = download_era5_from_cds(
    start_time, end_time,
    lon=restricted_area.lon_edges(),
    lat=restricted_area.lat_edges(),
    dlon=restricted_area.dlon(),
    dlat=restricted_area.dlat(),
    folder=temp_folder
)
```

**Comment by tovop** [comment]
For the record, the Python debugger prompt can be suppressed by setting the env variable PYTHONBREAKPOINT to zero.

One way is to run this code prior to the dnora code.

```python
import os
os.environ["PYTHONBREAKPOINT"] = "0"
```

**Comment by bjorkqvi** [comment]
Thanks for noticing this. It is a relic from some testing that was, for some reason not removed. I will fix it in the next release.
