### ISSUE TITLE
Error when exporting boundaries

### ISSUE THREAD

**Issue by tovop** [KonstantinChri/dnora#22]
Hi

I have setup a run in [era5_swan.zip](https://github.com/KonstantinChri/dnora/files/9432557/era5_swan.zip).

I encounter an error when exporting boundaries prior to a SWAN run.
![image](https://user-images.githubusercontent.com/25904755/186890672-33cc7241-e5bc-4dc7-9522-d80db597c9d8.png)

It can of course be a user error but I see that there is a inconsistency in lines 309-3011 of `dnora.bnd.write.py`  where the loop transcend the list of boundary points.

```python
def __call__(self, boundary: Boundary, filename: str) -> Tuple[str, str]:


    swan_bnd_points = boundary.grid.boundary_points()
    days = boundary.days()

    with open(filename, 'w') as file_out:
        file_out.write('SWAN   1\n')
        file_out.write('$ Data produced by '+boundary.data.source+'\n')
        file_out.write('TIME\n')
        file_out.write('          1\n')
        file_out.write('LONLAT\n')
        file_out.write('          '+format(len(boundary.x()))+'\n')
        for k in range(len(boundary.x())):
            file_out.write('   '+format(swan_bnd_points[k,0],'.4f')+'  '+format(swan_bnd_points[k,1],'.4f')+'\n')
        file_out.write('AFREQ\n')
```

I suggest the below modification where the number of boundary points is `len(swan_bnd_points)` and not `len(boundary.x())`. I can make a PR resolving this and issue #21 but I wanted to run it by you first.

```python
def __call__(self, boundary: Boundary, filename: str) -> Tuple[str, str]:


    swan_bnd_points = boundary.grid.boundary_points()
    days = boundary.days()

    with open(filename, 'w') as file_out:
        file_out.write('SWAN   1\n')
        file_out.write('$ Data produced by '+boundary.data.source+'\n')
        file_out.write('TIME\n')
        file_out.write('          1\n')
        file_out.write('LONLAT\n')
        file_out.write('          '+format(len(swan_bnd_points))+'\n')
        for k in range(len(swan_bnd_points)):
            file_out.write('   '+format(swan_bnd_points[k,0],'.4f')+'  '+format(swan_bnd_points[k,1],'.4f')+'\n')
```

Please advice how I can resolve this. Thanks.

**Comment by bjorkqvi** [comment]
Hi, 

Thanks, I think this is an issue with the way the boundary spectra are picked. Previously one spectra were chosen for each point (thus the length of those two variables were always equal), but now the default method has been changed to taking all spectra within the area, and letting SWAN do the interpolation.

The correction you are suggesting is therefore correct. If you have the time to do a pull request, then that would be really great. And as you said, you can then include the removing of the breakpoints also.

One more thing, since we are now picking all spectra in the area, we can now use a step=1 instead of step=20 (the examples have fallen behind). Since the default values is 1, you can do this by simply removing the step keword argument all together.

**Comment by tovop** [comment]
I'll do that. I encounter `remote: Permission to KonstantinChri/dnora.git denied to tovop` when I try to push. I guess you have to provide me/others write access to the repo.

**Comment by bjorkqvi** [comment]
I have now made a new release. You can pull the new main branch and check if this fixed the problem.

**Comment by tovop** [comment]
Super. I appreciate the swift support.

**Comment by tovop** [comment]
@bjorkqvi, I believe this issue is not completely resolved.

I think the the loop over `boundary.x()` and the call to `boundary.spec(..., x=[n])` is inconsistent with the above. 

Please suggest a permanent solution or a hotfix so that I can circumvent the problem. Thanks.

https://github.com/KonstantinChri/dnora/blob/55482e0b4e5fa969253a7e0a7ef520f2ec83294c/dnora/bnd/write.py#L328-L337

**Comment by tovop** [comment]
Please disregard my latest comment. It seems my pull failed so I did not get the entire update.

**Comment by KonstantinChri** [comment]
Dear @tovop ,

We will arrange a  dnora workshop on 26.10.2022 in Bergen. If you are interested, information and registration are [here](https://docs.google.com/forms/d/1cvzUHjthx6YgLUhi5FU9MQSyKZEjVZA9UHSa5Kqs3nc/)

Best regards,
@KonstantinChri
